"""
core/science.py
In-memory scientific catalog for waste details.
Used by the detector for instant lookups without DB round-trips.
"""

WASTE_CATALOG = {
    "plastic_bottle": {
        "category": "Plastic", "biodegradability": 0.01, "toxicity": 0.70,
        "radiation_level": 0.00, "recycling_score": 0.80, "decomposition_years": 450,
        "resin_code": "#1 PET", "carbon_footprint_kg": 3.4, "un_hazard_class": "None",
        "environmental_impact": "PET bottles persist 450+ years. Microplastics enter soil and ocean food chains.",
        "health_risk": "BPA and phthalates are endocrine disruptors. Linked to hormonal and developmental issues.",
        "scientific_notes": "Global PET production ~70 Mt/yr. Only ~30% recycled. Downcycled to polyester fiber.",
        "disposal_method": "Recycle stream #1 (PET). Rinse before disposal. Avoid single-use where possible.",
    },
    "plastic_bag": {
        "category": "Plastic", "biodegradability": 0.005, "toxicity": 0.60,
        "radiation_level": 0.00, "recycling_score": 0.30, "decomposition_years": 500,
        "resin_code": "#4 LDPE", "carbon_footprint_kg": 1.6, "un_hazard_class": "None",
        "environmental_impact": "Thin-film LDPE breaks into microplastics. Entangles marine megafauna.",
        "health_risk": "Ingested by seabirds and turtles. Airway obstruction in wildlife.",
        "scientific_notes": "Less than 5% of plastic bags are recycled globally. Banned in 60+ countries.",
        "disposal_method": "Return to store drop-off bins. Switch to reusable fabric bags.",
    },
    "aluminum_can": {
        "category": "Metal", "biodegradability": 0.00, "toxicity": 0.10,
        "radiation_level": 0.00, "recycling_score": 0.95, "decomposition_years": 200,
        "resin_code": "N/A", "carbon_footprint_kg": 0.9, "un_hazard_class": "None",
        "environmental_impact": "Mining bauxite destroys ecosystems. Smelting releases fluoride emissions.",
        "health_risk": "Minimal post-consumer health risk. Aluminum dust hazardous in manufacturing.",
        "scientific_notes": "Recycling saves 95% of production energy. Infinite quality retention.",
        "disposal_method": "Crush, rinse, place in metal recycling bin.",
    },
    "glass_bottle": {
        "category": "Glass", "biodegradability": 0.00, "toxicity": 0.00,
        "radiation_level": 0.00, "recycling_score": 0.90, "decomposition_years": 4000,
        "resin_code": "N/A", "carbon_footprint_kg": 0.9, "un_hazard_class": "None",
        "environmental_impact": "Inert in landfills. Production emits ~0.9 kg CO2/kg glass.",
        "health_risk": "Sharp edges cause lacerations. Chemically inert post-consumer.",
        "scientific_notes": "100% recyclable. Closed-loop recycling. Composed of SiO2, Na2CO3, CaCO3.",
        "disposal_method": "Separate by color. Recycle in designated glass bins.",
    },
    "paper": {
        "category": "Paper", "biodegradability": 0.80, "toxicity": 0.05,
        "radiation_level": 0.00, "recycling_score": 0.70, "decomposition_years": 0.08,
        "resin_code": "N/A", "carbon_footprint_kg": 1.1, "un_hazard_class": "None",
        "environmental_impact": "Deforestation pressure. Paper mills are top industrial water consumers.",
        "health_risk": "Inks may contain isopropanol VOCs. Generally low consumer risk.",
        "scientific_notes": "Recycling 1 tonne saves 17 trees, 26,000 L water, 4,000 kWh energy.",
        "disposal_method": "Recycle dry, clean paper. Compost soiled paper. Avoid laminated stock.",
    },
    "cardboard": {
        "category": "Cardboard", "biodegradability": 0.75, "toxicity": 0.05,
        "radiation_level": 0.00, "recycling_score": 0.85, "decomposition_years": 0.08,
        "resin_code": "N/A", "carbon_footprint_kg": 0.9, "un_hazard_class": "None",
        "environmental_impact": "High fiber content. Widely recycled in most municipalities.",
        "health_risk": "Low health risk. Staples and tape must be removed for clean recycling.",
        "scientific_notes": "Up to 80% recycled content possible. 7-9 recycling cycles achievable.",
        "disposal_method": "Flatten and bundle. Keep dry. Remove tape, foam, and staples.",
    },
    "food_waste": {
        "category": "Organic", "biodegradability": 0.95, "toxicity": 0.20,
        "radiation_level": 0.00, "recycling_score": 0.40, "decomposition_years": 0.05,
        "resin_code": "N/A", "carbon_footprint_kg": 2.5, "un_hazard_class": "None",
        "environmental_impact": "Landfill anaerobic decomposition produces CH4 — 28x GWP of CO2 over 100 yrs.",
        "health_risk": "Attracts vectors (rodents, insects). Mold produces mycotoxins.",
        "scientific_notes": "Food waste = 8% of global GHG. Home composting reduces landfill methane significantly.",
        "disposal_method": "Compost at home or use municipal green-waste collection.",
    },
    "battery": {
        "category": "Hazardous", "biodegradability": 0.00, "toxicity": 0.95,
        "radiation_level": 0.30, "recycling_score": 0.20, "decomposition_years": 100,
        "resin_code": "N/A", "carbon_footprint_kg": 12.5, "un_hazard_class": "UN3480 / Class 9",
        "environmental_impact": "Li-ion thermal runaway causes landfill fires. Pb, Cd, Hg leach into groundwater.",
        "health_risk": "Lead: neurological damage. Cadmium: kidney carcinogen. Lithium: caustic burns.",
        "scientific_notes": "Li-ion cobalt sourced partly from DRC conflict mines. Only 5% recycled globally.",
        "disposal_method": "NEVER in regular trash. Drop off at designated battery collection points.",
    },
    "electronics": {
        "category": "E-Waste", "biodegradability": 0.00, "toxicity": 0.85,
        "radiation_level": 0.10, "recycling_score": 0.60, "decomposition_years": 1000,
        "resin_code": "N/A", "carbon_footprint_kg": 300.0, "un_hazard_class": "Class 9 (select components)",
        "environmental_impact": "Contains Au, Ag, Cu, but also Pb, As, Hg, Cd. Informal recycling burns toxins.",
        "health_risk": "Pb solder causes neurological harm. Flame retardants are persistent organic pollutants.",
        "scientific_notes": "53.6 Mt e-waste generated in 2019. Only 17.4% formally recycled. Estimated value: $57B.",
        "disposal_method": "Take to certified e-waste facility (R2/e-Stewards). Wipe personal data first.",
    },
    "rubber_tire": {
        "category": "Rubber", "biodegradability": 0.01, "toxicity": 0.40,
        "radiation_level": 0.00, "recycling_score": 0.50, "decomposition_years": 2000,
        "resin_code": "N/A", "carbon_footprint_kg": 7.0, "un_hazard_class": "None",
        "environmental_impact": "Tire fires burn for years releasing dioxins and furans. Mosquito breeding sites.",
        "health_risk": "Combustion releases benzene, toluene, and polycyclic aromatic hydrocarbons.",
        "scientific_notes": "Tire-derived fuel, crumb rubber for playgrounds, and asphalt are recovery pathways.",
        "disposal_method": "Return to tire retailer or municipal tire collection event.",
    },
    "medical_waste": {
        "category": "Biohazard", "biodegradability": 0.10, "toxicity": 0.95,
        "radiation_level": 0.20, "recycling_score": 0.10, "decomposition_years": 100,
        "resin_code": "N/A", "carbon_footprint_kg": 0.0, "un_hazard_class": "Class 6.2 Infectious",
        "environmental_impact": "Infectious agents, sharps, cytotoxic drugs, and radioactive isotopes present.",
        "health_risk": "Needlestick injury transmits HIV, HBV, HCV. Cytotoxic drugs are carcinogenic.",
        "scientific_notes": "WHO: 15% of clinical waste is infectious or hazardous. High-temp incineration required.",
        "disposal_method": "Segregated yellow sharps containers. Incineration at >850 C mandatory.",
    },
    "radioactive_waste": {
        "category": "Nuclear", "biodegradability": 0.00, "toxicity": 1.00,
        "radiation_level": 0.95, "recycling_score": 0.00, "decomposition_years": 100000,
        "resin_code": "N/A", "carbon_footprint_kg": 0.0, "un_hazard_class": "Class 7 Radioactive",
        "environmental_impact": "High-level waste hazardous >10,000 years. Deep geological repositories required.",
        "health_risk": "Acute: Radiation sickness, death. Chronic: cancer, leukemia, hereditary effects (ICRP).",
        "scientific_notes": "Dominant isotopes: Cs-137 (T1/2=30yr), Sr-90 (T1/2=29yr). Stored in borosilicate glass.",
        "disposal_method": "Encapsulate in borosilicate glass. Licensed deep geological disposal facility only.",
    },
    "styrofoam": {
        "category": "Plastic", "biodegradability": 0.001, "toxicity": 0.50,
        "radiation_level": 0.00, "recycling_score": 0.10, "decomposition_years": 500,
        "resin_code": "#6 PS", "carbon_footprint_kg": 3.0, "un_hazard_class": "None",
        "environmental_impact": "EPS does not biodegrade. Breaks into persistent white beads ingested by marine life.",
        "health_risk": "Styrene monomer: IARC Group 2A possible carcinogen. Leaches into hot food.",
        "scientific_notes": "Only ~10% of EPS recycled due to low-density economics. Banned in 50+ US cities.",
        "disposal_method": "Avoid use. Drop off at EPS compactors. Never place in curbside recycling.",
    },
    "textile": {
        "category": "Textile", "biodegradability": 0.30, "toxicity": 0.20,
        "radiation_level": 0.00, "recycling_score": 0.40, "decomposition_years": 40,
        "resin_code": "N/A", "carbon_footprint_kg": 15.0, "un_hazard_class": "None",
        "environmental_impact": "Fast fashion = 92 Mt textile waste/yr. Synthetic fabrics shed 500,000 t microplastics/yr.",
        "health_risk": "Azo dyes, formaldehyde finishes can cause dermatitis and respiratory issues.",
        "scientific_notes": "Only 12-15% of textiles recycled globally. Most landfilled or incinerated.",
        "disposal_method": "Donate wearable items. Use textile-specific drop boxes. Avoid landfill.",
    },
    "organic_waste": {
        "category": "Organic", "biodegradability": 0.90, "toxicity": 0.10,
        "radiation_level": 0.00, "recycling_score": 0.50, "decomposition_years": 0.05,
        "resin_code": "N/A", "carbon_footprint_kg": 0.5, "un_hazard_class": "None",
        "environmental_impact": "Rapid anaerobic decomposition in landfills emits CH4. Composting diverts methane.",
        "health_risk": "Generally safe. May contain pesticide residues on treated plant matter.",
        "scientific_notes": "Composting reduces volume 50-70%. Vermicomposting produces premium soil amendment.",
        "disposal_method": "Compost on-site or use green-waste collection bin.",
    },
    "paint_can": {
        "category": "Hazardous", "biodegradability": 0.00, "toxicity": 0.80,
        "radiation_level": 0.00, "recycling_score": 0.15, "decomposition_years": 200,
        "resin_code": "N/A", "carbon_footprint_kg": 2.8, "un_hazard_class": "Class 3 Flammable (oil-based)",
        "environmental_impact": "VOC emissions contribute to ground-level ozone and smog formation.",
        "health_risk": "Solvents: neurotoxic. Lead-based paint: severe neurological damage in children.",
        "scientific_notes": "Water-based latex: lower VOC. Lead phase-out implemented 1978 (US). Earlier in EU.",
        "disposal_method": "Dry out latex paint before disposal. Oil-based: hazardous waste facility only.",
    },
    "aerosol_can": {
        "category": "Metal", "biodegradability": 0.00, "toxicity": 0.50,
        "radiation_level": 0.00, "recycling_score": 0.60, "decomposition_years": 200,
        "resin_code": "N/A", "carbon_footprint_kg": 1.5, "un_hazard_class": "Class 2.1 Flammable Gas",
        "environmental_impact": "Propellant VOCs degrade air quality. Some propellants are greenhouse gases.",
        "health_risk": "Flammable propellants (butane/propane) pose explosion risk if punctured or exposed to heat.",
        "scientific_notes": "Steel or aluminum shell is 100% recyclable after full discharge.",
        "disposal_method": "Fully empty the can. Recycle the metal shell. Never puncture or incinerate.",
    },
    "motor_oil": {
        "category": "Hazardous", "biodegradability": 0.00, "toxicity": 0.85,
        "radiation_level": 0.05, "recycling_score": 0.30, "decomposition_years": 200,
        "resin_code": "N/A", "carbon_footprint_kg": 4.0, "un_hazard_class": "Controlled waste",
        "environmental_impact": "One litre of used oil contaminates 1 million litres of groundwater.",
        "health_risk": "Polyaromatic hydrocarbons (PAHs) are carcinogenic. Contains neurotoxic heavy metals.",
        "scientific_notes": "Re-refining used oil produces base oil equivalent to virgin; saves 85% energy.",
        "disposal_method": "Take to automotive retailer or municipal HHW collection. Never pour down drains.",
    },
}

# YOLO class name -> internal waste key mapping
YOLO_TO_WASTE = {
    "bottle":       "plastic_bottle",
    "wine glass":   "glass_bottle",
    "cup":          "plastic_bottle",
    "fork":         "plastic_bottle",
    "knife":        "plastic_bottle",
    "spoon":        "plastic_bottle",
    "bowl":         "plastic_bottle",
    "banana":       "food_waste",
    "apple":        "food_waste",
    "sandwich":     "food_waste",
    "orange":       "food_waste",
    "broccoli":     "food_waste",
    "carrot":       "food_waste",
    "hot dog":      "food_waste",
    "pizza":        "food_waste",
    "donut":        "food_waste",
    "cake":         "food_waste",
    "cell phone":   "electronics",
    "laptop":       "electronics",
    "tv":           "electronics",
    "remote":       "electronics",
    "keyboard":     "electronics",
    "mouse":        "electronics",
    "hair drier":   "electronics",
    "clock":        "electronics",
    "book":         "paper",
    "scissors":     "plastic_bottle",
    "toothbrush":   "plastic_bottle",
    "backpack":     "textile",
    "handbag":      "textile",
    "suitcase":     "textile",
    "teddy bear":   "textile",
    "chair":        "textile",
    "couch":        "textile",
    "bed":          "textile",
    "umbrella":     "plastic_bottle",
    "vase":         "glass_bottle",
    "cardboard":    "cardboard",
    "box":          "cardboard",
    "paper":        "paper",
    "can":          "aluminum_can",
    "tin":          "aluminum_can",
}


def lookup(waste_name: str) -> dict:
    """Return catalog entry for a given waste key, with fallback by keyword match."""
    if waste_name in WASTE_CATALOG:
        return WASTE_CATALOG[waste_name]

    # Keyword fallback
    lower = waste_name.lower()
    for keyword, entry_key in [
        ("plastic", "plastic_bottle"), ("paper", "paper"), ("cardboard", "cardboard"),
        ("glass",   "glass_bottle"),   ("metal",  "aluminum_can"), ("can", "aluminum_can"),
        ("battery", "battery"),        ("food",   "food_waste"),   ("organic", "organic_waste"),
        ("electronic", "electronics"), ("nuclear","radioactive_waste"), ("radio","radioactive_waste"),
        ("medical", "medical_waste"),  ("textile","textile"),       ("rubber","rubber_tire"),
        ("paint",   "paint_can"),      ("aerosol","aerosol_can"),   ("oil",  "motor_oil"),
    ]:
        if keyword in lower:
            return WASTE_CATALOG[entry_key]

    # Generic fallback
    return {
        "category": "Unknown", "biodegradability": 0.3, "toxicity": 0.2,
        "radiation_level": 0.0, "recycling_score": 0.3, "decomposition_years": 50,
        "resin_code": "N/A", "carbon_footprint_kg": 1.0, "un_hazard_class": "Unknown",
        "environmental_impact": "Insufficient data for full environmental assessment.",
        "health_risk": "Risk level undetermined. Handle with standard precautions.",
        "scientific_notes": "Material type unrecognized. Manual classification recommended.",
        "disposal_method": "Consult local municipal waste guidelines.",
    }
